### ISSUE TITLE
Domain grouping puts all two level country domains e.g *.co.uk as one group

### ISSUE THREAD

**Issue by reification-zz** [mickaphd/SimpleCookie#1]
Domain grouping puts all two level country domains e.g *.co.uk as one group thus I cannot separately manage amazon.co.uk and bbc.co.uk

This seems to apply to all cases such as co.jp, org.uk and edu.au

**Comment by mickaphd** [comment]
Good catch! I’ll try to fix this and push an update ASAP.

**Comment by mickaphd** [comment]
I have uploaded a pre-release to Github. I tried several things, like implementing sorting by increasing the main domain from -2 to -3 (from the right to the left), which I think worked for your problem, but was a bit annoying for others. So I created a new preferences menu and implemented this as a setting. You will need to change the default -2 to -3 in your case. I will test the addon a bit more before releasing it to the store. Feel free to reopen a ticket if you have any other ideas or comments. Hopefully it will work out. Cheers.

**Comment by mickaphd** [comment]
Hey, I just wanted to update you that the add-on is now using a comprehensive list of exceptions for specific Second Level Domains (SLDs) used in various countries (it has been a while, in fact). I believe this is much better, but please feel free to reopen a ticket if you have any additional feedback.

My best,  
M
